"""End-to-end inference example for the ORena SAVE FOCUS challenge.

Pipeline:
  1. Load a pre-split FocusDataset (see data_preparation.py for how to create one)
  2. Wrap it in FocusVideoDataset to produce on-the-fly temporary clips
  3. Run a Qwen3-VL model over every test sample
  4. Collect Responses and evaluate with the Evaluator

Prerequisites
-------------
    pip install orena-focus qwen-vl-utils transformers accelerate

The dataset must have been downloaded and split beforehand — see
``examples/data_preparation.py`` for the full preparation pipeline.
"""

import logging
from multiprocessing.connection import answer_challenge
import time
import warnings
import os
import torch
from progiter import ProgIter
from qwen_vl_utils import process_vision_info
import json
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig
from focus import FO_DEFINITIONS_FILE, FocusConfig, set_config
from focus.data.base_dataset import FocusDataset
from focus.data.data_models import Response
from focus.data.video_dataset import FocusVideoDataset, VideoSample
from focus.enums import DatasetSplit, Track
from focus.evaluation.evaluator import Evaluator
from peft import PeftModel
import random
random.seed(0)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────
# All tuneable parameters in one place.

CONFIG = {
    "root_dir": "/iopsstor/scratch/cscs/lpanta32/focus",
    "model_id": "/iopsstor/scratch/cscs/lpanta32/checkpoints/Qwen3-VL-8B-Instruct",
    "device": "cuda:2" if torch.cuda.is_available() else "cpu",
    "dataset_name": "lapchole",
    "track": Track.SEGMENT,
    "video_stride": 25,  # keep every 25th frame (1 fps at 25 fps source)
    "video_resolution": (640, 360),
    "use_overlay": True,  # use timestamp-overlaid videos
    "num_eval": 1000,  # set to None to evaluate all test samples
    "output_dir": "/capstor/store/cscs/swissai/a0264/lpanta32/orena-focus",  # set to a path to persist results CSV files
}

SYSTEM_PROMPT = (
    "You are a surgical assistant. You are given endoscopic video from a "
    "minimally invasive procedure. Analyze the footage and answer the surgical "
    "question based on the visual evidence. Be precise and concise.\n\n"
    + FO_DEFINITIONS_FILE.read_text()
)


# ── Inference engine ──────────────────────────────────────────────────


class QwenInferenceEngine:
    """Qwen3-VL model wrapper for FOCUS challenge inference.

    Parameters
    ----------
    model_id : str
        HuggingFace model identifier (e.g. ``"Qwen/Qwen3-VL-4B-Instruct"``).
    device : str
        Torch device string (``"cpu"`` or ``"cuda"``).

    Notes
    -----
    Call :meth:`load` before :meth:`predict` to initialise model weights.
    """

    def __init__(self, model_id: str, device: str) -> None:
        self.model_id = model_id
        self.device = device
        self.model = None
        self.processor = None

    def load(self) -> None:
        """Load the processor and model weights from HuggingFace Hub."""
        logger.info(f"Loading model {self.model_id!r} on device {self.device!r}…")
        self.model = AutoModelForImageTextToText.from_pretrained(
            self.model_id,
            torch_dtype=torch.bfloat16,
            attn_implementation="eager",
            device_map="auto",
            trust_remote_code=True,
        )
        # self.model = PeftModel.from_pretrained(
        #     base, "/scratch/lpanta/checkpoints/qwen3vl-8b-lora_overlay/final"
        # ).eval()
        self.processor = AutoProcessor.from_pretrained(self.model_id)
        if hasattr(self.model, "generation_config"):
            self.model.generation_config.max_length = None
        logger.info("Model ready.")

    def predict(self, question, fps, video_path) -> str:
        """Run inference on one sample and clean up the temporary clip.


        Returns
        -------
        str
            The raw text generated by the model, or an error message prefixed
            with ``"Inference Error:"`` if generation fails.
        """
        try:
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "video",
                            "video": video_path,
                            "fps": fps//24,
                            "video_metadata": {
                                "fps": fps,
                                "width": CONFIG["video_resolution"][0],
                                "height": CONFIG["video_resolution"][1],
                            },
                        },
                        {"type": "text", "text": question},
                    ],
                },
            ]

            text = self.processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            image_inputs, video_inputs = process_vision_info(messages)
            inputs = self.processor(
                text=[text],
                images=image_inputs,
                videos=video_inputs,
                padding=True,
                return_tensors="pt",
            ).to(self.device)
            print(video_inputs[0].shape)
            print("video_grid_thw:", inputs.video_grid_thw)

            with torch.no_grad():
                gen_ids = self.model.generate(**inputs, max_new_tokens=128)
                trimmed = [ids[len(inputs.input_ids[0]) :] for ids in gen_ids]
                return self.processor.batch_decode(trimmed, skip_special_tokens=True)[0]

        except Exception as exc:
            logger.error(f"[{video_path}] Inference failed: {exc}")
            return f"Inference Error: {str(exc)[:50]}"

        # finally:
        #     sample.video_path.unlink(missing_ok=True)
        #


# ── Main pipeline ─────────────────────────────────────────────────────


def main() -> None:
    # ── 1. Configure and load dataset ────────────────────────────────
    # Run examples/data_preparation.py first to download and split the dataset.
    set_config(FocusConfig(root_dir=CONFIG["root_dir"]))

    base_dataset = FocusDataset(
        dataset=CONFIG["dataset_name"],
        split=DatasetSplit.TEST,
        track=CONFIG["track"],
    )
    n_total = len(base_dataset)
    n_eval = min(CONFIG["num_eval"], n_total) if CONFIG["num_eval"] else n_total
    logger.info(f"Evaluating {n_eval}/{n_total} test samples.")

    # ── 2. Load model ─────────────────────────────────────────────────
    engine = QwenInferenceEngine(CONFIG["model_id"], CONFIG["device"])
    engine.load()
    with open(
        os.path.join(CONFIG["root_dir"], "lapchole_test.json"),
        "r",
        encoding="utf-8",
    ) as file:
        dataset_json = json.load(file)
    print(len(list(dataset_json.keys())))
    # ── 3. Inference loop ─────────────────────────────────────────────
    requests, references, responses = [], [], []
    count_index = 0
    for i, sample in enumerate(ProgIter(base_dataset, total=n_eval, desc="Inference")):
        if count_index >= n_eval:
            break
        count_index = count_index + 1

        t0 = time.perf_counter()
        try:
            qid = sample[0].qID
            json_sample = dataset_json[qid]
        except Exception as e:
            print(f"Skipping due to error as {e}")
            continue

        fps = json_sample[1]["content"][0]["fps"]//2
        video_path = json_sample[1]["content"][0]["video"]
        prediction = engine.predict(sample[0].question, fps, video_path)
        latency = time.perf_counter() - t0

        requests.append(sample[0])
        references.append(sample[1])
        responses.append(
            Response(
                qID=sample[0].qID,
                content=prediction,
                latency=latency,
            )
        )
        print(
            "Index: ",
            i,
            "\n Question: ",
            sample[0].question,
            "\n Prediction: ",
            prediction,
            "\n GT: ",
            sample[1].answer,
            "\n Latency: ",
            latency,
        )
    if not responses:
        warnings.warn("No test samples were processed. Check dataset status.")
        return

    # ── 4. Evaluation ─────────────────────────────────────────────────
    results_df, summary_df = Evaluator(judge_kwargs={"device": CONFIG["device"]}).run(
        requests=requests,
        references=references,
        responses=responses,
        output_dir=CONFIG["output_dir"],
    )

    print(summary_df.to_string(index=False))


if __name__ == "__main__":
    main()