"""End-to-end inference example for the ORena SAVE FOCUS challenge.

Pipeline:
  1. Load a pre-split FocusDataset (see data_preparation.py for how to create one)
  2. Wrap it in FocusVideoDataset to produce on-the-fly temporary clips
  3. Run a MedVLM / Qwen2.5-VL model over every test sample with variable FPS
  4. Collect Responses and evaluate with the Evaluator

Prerequisites
-------------
    pip install orena-focus qwen-vl-utils transformers accelerate
"""

import json
import logging
import os
import random
import time
import warnings
import torch
from progiter import ProgIter
from qwen_vl_utils import process_vision_info
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

from focus import FO_DEFINITIONS_FILE, FocusConfig, set_config
from focus.data.base_dataset import FocusDataset
from focus.data.data_models import Response
from focus.enums import DatasetSplit, Track
from focus.evaluation.evaluator import Evaluator

random.seed(0)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────

CONFIG = {
    "root_dir": "/iopsstor/scratch/cscs/lpanta32/focus",
    "model_id": "/iopsstor/scratch/cscs/lpanta32/checkpoints/uAI-NEXUS-MedVLM-1.0a-7B-RL",
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "dataset_name": "lapchole",
    "track": Track.SEGMENT,
    "target_fps": 1.0,  # Variable sampling FPS (e.g., 1.0 = sample 1 frame per second)
    "video_resolution": (640, 360),
    "use_overlay": True,
    "num_eval": None,  # Set to None to evaluate all test samples
    "output_dir": "/capstor/store/cscs/swissai/a0264/lpanta32/orena-focus",
}

SYSTEM_PROMPT = (
    "You are a surgical assistant. You are given endoscopic video from a "
    "minimally invasive procedure. Analyze the footage and answer the surgical "
    "question based on the visual evidence. Be precise and concise.\n\n"
    + FO_DEFINITIONS_FILE.read_text()
)


# ── Inference engine ──────────────────────────────────────────────────


class QwenInferenceEngine:
    """Qwen2.5-VL / MedVLM model wrapper for FOCUS challenge inference.

    Parameters
    ----------
    model_id : str
        Path or HuggingFace identifier for Qwen2.5-VL architecture model.
    device : str
        Torch device string ("cpu" or "cuda").
    """

    def __init__(self, model_id: str, device: str) -> None:
        self.model_id = model_id
        self.device = device
        self.model = None
        self.processor = None

    def load(self) -> None:
        """Load the processor and Qwen2.5-VL model weights."""
        logger.info(f"Loading model {self.model_id!r}…")
        
        self.model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            self.model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )
        self.processor = AutoProcessor.from_pretrained(self.model_id)

        if hasattr(self.model, "generation_config"):
            self.model.generation_config.max_length = None
        logger.info("Model ready.")

    def predict(self, question: str, video_path: str, fps: float = 1.0) -> str:
        """Run inference on one video sample with specified target frame rate.

        Parameters
        ----------
        question : str
            The prompt or question about the surgical video.
        video_path : str
            Path to the target video file.
        fps : float, optional
            Target sampling rate (frames per second), by default 1.0.

        Returns
        -------
        str
            The text response generated by the model.
        """
        try:
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "video",
                            "video": video_path,
                            "fps": fps,  # Dynamically samples frames at 'fps' frame rate
                            # Alternatively use uniform frame count:
                            # "nframes": 32, 
                        },
                        {"type": "text", "text": question},
                    ],
                },
            ]

            text = self.processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            image_inputs, video_inputs = process_vision_info(messages)

            inputs = self.processor(
                text=[text],
                images=image_inputs,
                videos=video_inputs,
                padding=True,
                return_tensors="pt",
            ).to(self.model.device)

            with torch.no_grad():
                output_ids = self.model.generate(**inputs, max_new_tokens=128)
                generated_ids = [
                    out[len(inp):] for inp, out in zip(inputs.input_ids, output_ids)
                ]
                response = self.processor.batch_decode(
                    generated_ids, skip_special_tokens=True
                )[0]

            return response

        except Exception as exc:
            logger.error(f"[{video_path}] Inference failed: {exc}")
            return f"Inference Error: {str(exc)[:50]}"


# ── Main pipeline ─────────────────────────────────────────────────────


def main() -> None:
    # ── 1. Configure and load dataset ────────────────────────────────
    set_config(FocusConfig(root_dir=CONFIG["root_dir"]))

    base_dataset = FocusDataset(
        dataset=CONFIG["dataset_name"],
        split=DatasetSplit.TEST,
        track=CONFIG["track"],
    )

    n_total = len(base_dataset)
    n_eval = min(CONFIG["num_eval"], n_total) if CONFIG["num_eval"] else n_total
    logger.info(f"Evaluating {n_eval}/{n_total} test samples.")

    # ── 2. Load model ─────────────────────────────────────────────────
    engine = QwenInferenceEngine(CONFIG["model_id"], CONFIG["device"])
    engine.load()

    json_path = os.path.join(CONFIG["root_dir"], "lapchole_test_overlay.json")
    with open(json_path, "r", encoding="utf-8") as file:
        dataset_json = json.load(file)

    # ── 3. Inference loop ─────────────────────────────────────────────
    requests, references, responses = [], [], []
    count_index = 0
    random_indices = set(random.sample(range(0, n_total), n_eval))

    for i, sample in enumerate(ProgIter(base_dataset, total=n_eval, desc="Inference")):
        if count_index >= n_eval:
            break
        if i not in random_indices:
            continue
        count_index += 1

        t0 = time.perf_counter()
        try:
            qid = sample[0].qID
            json_sample = dataset_json[qid]
            video_path = json_sample[1]["content"][0]["video"]
        except Exception as e:
            logger.warning(f"Skipping index {i} due to error: {e}")
            continue

        # Extract variable sampling rate (or use custom logic per video)
        sampling_fps = CONFIG["target_fps"]

        prediction = engine.predict(
            question=sample[0].question,
            video_path=video_path,
            fps=sampling_fps,
        )
        latency = time.perf_counter() - t0

        requests.append(sample[0])
        references.append(sample[1])
        responses.append(
            Response(
                qID=sample[0].qID,
                content=prediction,
                latency=latency,
            )
        )

        print(
            f"Index: {i}\n"
            f"Question: {sample[0].question}\n"
            f"Prediction: {prediction}\n"
            f"GT: {sample[1].answer}\n"
            f"Latency: {latency:.2f}s\n"
        )

    if not responses:
        warnings.warn("No test samples were processed. Check dataset status.")
        return

    # ── 4. Evaluation ─────────────────────────────────────────────────
    results_df, summary_df = Evaluator(
        judge_kwargs={"device": CONFIG["device"]}
    ).run(
        requests=requests,
        references=references,
        responses=responses,
        output_dir=CONFIG["output_dir"],
    )

    print(summary_df.to_string(index=False))


if __name__ == "__main__":
    main()